INSERT INTO Categories (Id, Name, Description)
VALUES
    (1, 'Keyboard', 
     'An input device used to enter text, commands, and shortcuts into a computer, available in various layouts and switch types for typing, gaming, and professional use.'),
    
    (2, 'Mouse', 
     'A pointing device that allows users to interact with graphical interfaces through movement, clicks, and scrolling, with variations optimized for precision, ergonomics, or gaming.'),
    
    (3, 'Case', 
     'The enclosure that houses and protects computer components while providing airflow, cable management, and physical mounting for hardware.'),
    
    (4, 'Graphics Card', 
     'A hardware component responsible for rendering images, video, and 3D graphics, containing a GPU and dedicated memory to handle intensive visual workloads.'),
    
    (5, 'CPU', 
     'The central processing unit that executes instructions and performs calculations, acting as the primary computational engine of the computer.'),
    
    (6, 'Power Supply', 
     'A component that converts electrical power from an outlet into usable power for internal computer parts, ensuring stable voltage and system reliability.'),
    
    (7, 'Motherboard', 
     'The main circuit board that connects and allows communication between all hardware components, including the CPU, memory, storage, and expansion devices.'),
    
    (8, 'Cooler', 
     'A thermal solution designed to dissipate heat from components such as the CPU or GPU, using air or liquid to maintain safe operating temperatures.'),
    
    (9, 'Monitor', 
     'An output device that displays visual information generated by the computer, varying in size, resolution, refresh rate, and panel technology.'),
    
    (10, 'RAM', 
     'Volatile memory used to temporarily store data and instructions actively required by the CPU, enabling fast access and multitasking.'),
    
    (11, 'SSD', 
     'A solid-state storage device that uses flash memory to store data, offering high speed, low latency, and no moving parts.'),
    
    (12, 'HDD', 
     'A mechanical storage device that stores data on spinning magnetic disks, providing large capacity at a lower cost compared to solid-state storage.')
;

--SELECT Name, NameLength = LEN(Name), DescriptionLength = LEN(Description) FROM Categories ORDER BY NameLength DESC;