INSERT INTO Currencies (Id, ISO3, Name)
VALUES
    (1, 'AED', 'UAE Dirham'),
    (2, 'AFN', 'Afghani'),
    (3, 'ALL', 'Lek'),
    (4, 'AMD', 'Armenian Dram'),
    (5, 'ANG', 'Netherlands Antillean Guilder'),
    (6, 'AOA', 'Kwanza'),
    (7, 'ARS', 'Argentine Peso'),
    (8, 'AUD', 'Australian Dollar'),
    (9, 'AWG', 'Aruban Florin'),
    (10, 'AZN', 'Azerbaijan Manat'),
    (11, 'BAM', 'Convertible Mark'),
    (12, 'BBD', 'Barbados Dollar'),
    (13, 'BDT', 'Taka'),
    (14, 'BGN', 'Bulgarian Lev'),
    (15, 'BHD', 'Bahraini Dinar'),
    (16, 'BIF', 'Burundi Franc'),
    (17, 'BMD', 'Bermudian Dollar'),
    (18, 'BND', 'Brunei Dollar'),
    (19, 'BOB', 'Boliviano'),
    (20, 'BRL', 'Brazilian Real'),
    (21, 'BSD', 'Bahamian Dollar'),
    (22, 'BTN', 'Ngultrum'),
    (23, 'BWP', 'Pula'),
    (24, 'BYN', 'Belarusian Ruble'),
    (25, 'BZD', 'Belize Dollar'),
    (26, 'CAD', 'Canadian Dollar'),
    (27, 'CDF', 'Congolese Franc'),
    (28, 'CHF', 'Swiss Franc'),
    (29, 'CLP', 'Chilean Peso'),
    (30, 'CNY', 'Yuan Renminbi'),
    (31, 'COP', 'Colombian Peso'),
    (32, 'CRC', 'Costa Rican Colon'),
    (33, 'CUP', 'Cuban Peso'),
    (34, 'CZK', 'Czech Koruna'),
    (35, 'DKK', 'Danish Krone'),
    (36, 'DOP', 'Dominican Peso'),
    (37, 'DZD', 'Algerian Dinar'),
    (38, 'EGP', 'Egyptian Pound'),
    (39, 'ERN', 'Nakfa'),
    (40, 'ETB', 'Ethiopian Birr'),
    (41, 'EUR', 'Euro'),
    (42, 'FJD', 'Fiji Dollar'),
    (43, 'GBP', 'Pound Sterling'),
    (44, 'GEL', 'Lari'),
    (45, 'GHS', 'Ghana Cedi'),
    (46, 'GIP', 'Gibraltar Pound'),
    (47, 'GMD', 'Dalasi'),
    (48, 'GNF', 'Guinean Franc'),
    (49, 'GTQ', 'Quetzal'),
    (50, 'GYD', 'Guyana Dollar'),
    (51, 'HKD', 'Hong Kong Dollar'),
    (52, 'HNL', 'Lempira'),
    (53, 'HRK', 'Kuna'),
    (54, 'HTG', 'Gourde'),
    (55, 'HUF', 'Forint'),
    (56, 'IDR', 'Rupiah'),
    (57, 'ILS', 'New Israeli Shekel'),
    (58, 'INR', 'Indian Rupee'),
    (59, 'IQD', 'Iraqi Dinar'),
    (60, 'IRR', 'Iranian Rial'),
    (61, 'ISK', 'Iceland Krona'),
    (62, 'JMD', 'Jamaican Dollar'),
    (63, 'JOD', 'Jordanian Dinar'),
    (64, 'JPY', 'Yen'),
    (65, 'KES', 'Kenyan Shilling'),
    (66, 'KGS', 'Som'),
    (67, 'KHR', 'Riel'),
    (68, 'KMF', 'Comorian Franc'),
    (69, 'KPW', 'North Korean Won'),
    (70, 'KRW', 'Won'),
    (71, 'KWD', 'Kuwaiti Dinar'),
    (72, 'KZT', 'Tenge'),
    (73, 'LAK', 'Lao Kip'),
    (74, 'LBP', 'Lebanese Pound'),
    (75, 'LKR', 'Sri Lanka Rupee'),
    (76, 'LRD', 'Liberian Dollar'),
    (77, 'LSL', 'Loti'),
    (78, 'LYD', 'Libyan Dinar'),
    (79, 'MAD', 'Moroccan Dirham'),
    (80, 'MDL', 'Moldovan Leu'),
    (81, 'MGA', 'Malagasy Ariary'),
    (82, 'MKD', 'Denar'),
    (83, 'MMK', 'Kyat'),
    (84, 'MNT', 'Tugrik'),
    (85, 'MOP', 'Pataca'),
    (86, 'MRU', 'Ouguiya'),
    (87, 'MUR', 'Mauritius Rupee'),
    (88, 'MVR', 'Rufiyaa'),
    (89, 'MWK', 'Malawi Kwacha'),
    (90, 'MXN', 'Mexican Peso'),
    (91, 'MYR', 'Malaysian Ringgit'),
    (92, 'MZN', 'Mozambique Metical'),
    (93, 'NAD', 'Namibia Dollar'),
    (94, 'NGN', 'Naira'),
    (95, 'NIO', 'Cordoba Oro'),
    (96, 'NOK', 'Norwegian Krone'),
    (97, 'NPR', 'Nepalese Rupee'),
    (98, 'NZD', 'New Zealand Dollar'),
    (99, 'OMR', 'Rial Omani'),
    (100, 'PAB', 'Balboa'),
    (101, 'PEN', 'Sol'),
    (102, 'PGK', 'Kina'),
    (103, 'PHP', 'Philippine Peso'),
    (104, 'PKR', 'Pakistan Rupee'),
    (105, 'PLN', 'Zloty'),
    (106, 'PYG', 'Guarani'),
    (107, 'QAR', 'Qatari Rial'),
    (108, 'RON', 'Romanian Leu'),
    (109, 'RSD', 'Serbian Dinar'),
    (110, 'RUB', 'Russian Ruble'),
    (111, 'RWF', 'Rwanda Franc'),
    (112, 'SAR', 'Saudi Riyal'),
    (113, 'SDG', 'Sudanese Pound'),
    (114, 'SEK', 'Swedish Krona'),
    (115, 'SGD', 'Singapore Dollar'),
    (116, 'SLL', 'Leone'),
    (117, 'SOS', 'Somali Shilling'),
    (118, 'SRD', 'Surinam Dollar'),
    (119, 'SSP', 'South Sudanese Pound'),
    (120, 'SYP', 'Syrian Pound'),
    (121, 'THB', 'Baht'),
    (122, 'TJS', 'Somoni'),
    (123, 'TMT', 'Turkmenistan New Manat'),
    (124, 'TND', 'Tunisian Dinar'),
    (125, 'TOP', 'Pa’anga'),
    (126, 'TRY', 'Turkish Lira'),
    (127, 'TTD', 'Trinidad and Tobago Dollar'),
    (128, 'TWD', 'New Taiwan Dollar'),
    (129, 'TZS', 'Tanzanian Shilling'),
    (130, 'UAH', 'Hryvnia'),
    (131, 'UGX', 'Uganda Shilling'),
    (132, 'USD', 'US Dollar'),
    (133, 'UYU', 'Peso Uruguayo'),
    (134, 'UZS', 'Uzbekistan Sum'),
    (135, 'VES', 'Bolívar Soberano'),
    (136, 'VND', 'Dong'),
    (137, 'VUV', 'Vatu'),
    (138, 'WST', 'Tala'),
    (139, 'XAF', 'CFA Franc BEAC'),
    (140, 'XCD', 'East Caribbean Dollar'),
    (141, 'XOF', 'CFA Franc BCEAO'),
    (142, 'XPF', 'CFP Franc'),
    (143, 'YER', 'Yemeni Rial'),
    (144, 'ZAR', 'Rand'),
    (145, 'ZMW', 'Zambian Kwacha'),
    (146, 'ZWL', 'Zimbabwe Dollar')
;